name: "upload-artifact-release"
description: "uploads the JAR as an artifact"

inputs:
  artifact-name:
    description: "The name of the artifact"
    default: "built-jar"
  artifact-path:
    description: "The path to the artifact"
    default: "build/libs"
  release-version:
    description: "The version of the release"
    default: "${{ github.ref_name }}"
  release-files:
    description: "The files to upload as artifacts"
    default: "build/libs/*.jar"
  release-latest:
    description: "Whether to make the release the latest"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Download JAR Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    - name: Upload JAR to Release
      id: upload-release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ inputs.release-files }}
        generate_release_notes: true
        make_latest: ${{ inputs.release-latest }}
        tag_name: ${{ inputs.release-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}