name: "upload-artifact-release"
description: "uploads the JAR as an artifact"

inputs:
  artifact_name:
    description: "The name of the artifact"
    default: "built-jar"
  artifact_path:
    description: "The path to the artifact"
    default: "build/libs"
  release_version:
    description: "The version of the release"
    default: "${{ github.ref_name }}"
  release_files:
    description: "The files to upload as artifacts"
    default: "build/libs/*.jar"
  release_latest:
    description: "Whether to make the release the latest"
    default: "true"
  github_token:
    description: "The GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download JAR Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_path }}

    - name: Upload JAR to Release
      id: upload-release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ inputs.release_files }}
        generate_release_notes: true
        make_latest: ${{ inputs.release_latest }}
        tag_name: ${{ inputs.release_version }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}