name: docker-upload-artifact
description: "compiles and uploads the artifact with Dockerfile, and releases"

inputs:
  artifact_name:
    description: "The name of the artifact"
    default: "built-jar"
  artifact_path:
    description: "The path to the artifact"
    default: "build/libs"
  github_token:
    description: "The GitHub token"
    required: true


runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download JAR Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_path }}

    - name: Build Docker Image
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        TAG=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$REPO_NAME:$TAG .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Push Docker Image
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        TAG=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$REPO_NAME:$TAG
