name: "java-build"
description: "Builds a Java project and uploads as release"
author: "TropicalShadow"

inputs:
  gradle-command:
    description: "The command executed by Gradle to build the project"
    default: "./gradlew clean shadowJar --no-daemon"
  java_version:
    description: "The Java version to build with"
    default: "21"
  java_distribution:
    description: "The Java distribution to build with"
    default: "temurin"
  maven_username:
    description: "The username for the Maven repository"
    required: true
  maven_secret:
    description: "The secret for the Maven repository"
    required: true
  github_token:
    description: "The GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"

    - name: "Get Commit Hash"
      id: "commit"
      uses: "pr-mpt/actions-commit-hash@v2"

    - name: "Validate Gradle wrapper"
      uses: "gradle/actions/wrapper-validation@v4"

    - name: "Set up JDK"
      uses: "actions/setup-java@v2"
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: "Build with Gradle"
      shell: "bash"
      env:
        MAVEN_USERNAME: ${{ inputs.maven_username }}
        MAVEN_SECRET: ${{ inputs.maven_secret }}
        COMMIT_HASH: "${{ steps.commit.outputs.hash }}"
        COMMIT_HASH_SHORT: "${{ steps.commit.outputs.short }}"
      run: "${{ inputs.gradle_command }}"

    - name: Upload JAR to Release
      id: upload-release
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/*.jar
        generate_release_notes: true
        tag_name: ${{ steps.commit.outputs.short }}
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}